### ISSUE TITLE
Document the impact on the transport with leased messages

### ISSUE THREAD

**Issue by SeanFeldman** [ramonsmits/NServiceBus.RateLimiter#2]
The [current documentation](https://github.com/ramonsmits/NServiceBus.RateLimiter#important) is incomplete and doesn't elaborate on the problem associated with the transport that lease messages and how delaying those messages can cause problems. All it has is the following:

> If you use lease based transport (Azure Storage Queues).

For ASB, a better solution is to reduce prefetching rather than using a rate limiter. At least until ASB introduces infinite lock duration.

**Comment by ramonsmits** [comment]
@SeanFeldman agreed that it would be advised to disable or minimize prefetching. However, rate limiting is something different the prefetching. Prefetching is used to reduce latency and ensure the concurrency limit is maxed so ensure a message is immediately ready for processing.

IMHO, prefetching should be disabled by default for ANY lease based transport and only be enabled if the process lag causes throughput issues.
