### ISSUE TITLE
Disable lease warning for RabbitMQ transport

### ISSUE THREAD

**Issue by cafedo** [ramonsmits/NServiceBus.RateLimiter#4]
Hi all,
I think that the warning log entry, written when the delay takes more then 5 seconds, is not relevant when you are using RabbitMQ on-premise as a transport; I mean, in this case you don't have to deal with lease time or distributed transaction.
What about disable this log entry for RabbitMQ or other specific transport?

**Comment by ramonsmits** [comment]
@cafedo True, RabbitMQ isn't affected in such a way. How about an API like:

```c#
var rateLimiting = endpointConfiguration.ApplyRateLimiting(10);
rateLimiting.WarningThresshold = TimeSpan.FromSeconds(60);
```

**Comment by ramonsmits** [comment]
Added ability to disable in https://github.com/ramonsmits/NServiceBus.RateLimiter/releases/tag/3.1.0
